name: Vivado_CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: [make, vivado]
    steps:
    - uses: actions/checkout@v4
    - name: Simulations
      shell: bash
      run: |
        ./ci.sh
